### ISSUE TITLE
Annotations don't work at Grafana 2.6

### ISSUE THREAD

**Issue by poxin13** [alexanderzobnin/grafana-zabbix#133]
TypeError: Cannot read property 'from' of undefined
at ZabbixAPIDatasource.annotationQuery

![Image of Issue](http://i.imgur.com/GxP66tn.png)

**Comment by poxin13** [comment]
No longer getting any errors when adding an Annotation, however they are not displaying in the graphs.

**Comment by volter** [comment]
Maybe now? :)

https://github.com/alexanderzobnin/grafana-zabbix/pull/114

**Comment by poxin13** [comment]
No luck with #114 either unfortunately using rangeRaw.from or range.from

**Comment by alexanderzobnin** [comment]
@poxin13 I added fix to [panel-triggers](https://github.com/alexanderzobnin/grafana-zabbix/tree/panel-triggers) branch (it's for Grafana 3.0). I tested with latest pre-build of Grafana 3.0 and it works. I will add fix for 2.6 soon.

**Comment by alexanderzobnin** [comment]
@poxin13 try update from [develop](https://github.com/alexanderzobnin/grafana-zabbix/tree/develop). I merged @volter patch and fix them (e is undefined error).

**Comment by poxin13** [comment]
Nah, still no go on 2.6 - still nothing displayed on the graphs.

**Comment by poxin13** [comment]
This is now working from develop branch commits.
