### ISSUE TITLE
Cannot create multi-dimensional alert rule

### ISSUE THREAD

**Issue by BrunoBlanes** [alexanderzobnin/grafana-zabbix#1426]
## Describe the bug
I get the following error when the alert fires:
```
["invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}"]()
```

## Expected behavior
Expected to get multiple alert instances.

## Screenshots
![image](https://user-images.githubusercontent.com/28227097/163039160-f02888d9-7965-46d1-8089-fff98c085603.png)

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.4.6   | 6.0.3  | 4.2.5                 |

**Comment by alexanderzobnin** [comment]
Hi! Initially I thought it's related to missing labels (which was fixed in f0842bfb7e0c0c912f00f6f67c2226dacccf1f40). But I tried to debug similar alert rule and found that there's some unclear error. Error that actually causes a problem sounds like `looks like time series data, only reduced data can be alerted on`. So I added reduce expression to the alert query and it's working:

<img width="1317" alt="Screenshot 2022-04-27 at 13 31 08" src="https://user-images.githubusercontent.com/4932851/165499114-641ba5d7-6e95-4e0b-a93f-409104f50127.png">

<img width="1299" alt="Screenshot 2022-04-27 at 13 31 17" src="https://user-images.githubusercontent.com/4932851/165499239-88285607-680d-496a-8da2-c9d8a457c64b.png">

**Comment by BrunoBlanes** [comment]
I'm sorry @alexanderzobnin, but it still doesn't work, I tried to make it resemble your example as best as possible as you can see below:

![image](https://user-images.githubusercontent.com/28227097/165832247-bcc9e48b-c720-4c14-a437-3a8a58b1688b.png)

I did notice that my `B` expression is returning its values without any tags, different from your example. Am I doing something wrong here?
