### ISSUE TITLE
Performance issue when having a lot of metrics

### ISSUE THREAD

**Issue by Krazylee** [alexanderzobnin/grafana-zabbix#148]
Hi, I configured a dashboard with 9 panels and each panel has 8 metrics(8 nodes).
I think that's not very much compared to the example screenshot.
But the load speed is quite slow.

Looking around the requests and the datasource code, I find that every metric requires at least four requests:
1. get host data
2. get application data
3. get item id
4. use item id to get history data

So if we want to monitor 9 metrics of 8 nodes, we will send 9 * 8 * 4 = 288 requests, plus the user.login requests, we may reach 300, a lot of requests will be queued.

I think we can cache the first 3 request data into local storage, host/application/item data are quite static, we use 3 requests to get the item id, this is a big waste.

Any suggestions?

**Comment by alexanderzobnin** [comment]
Hi! I working on this problem - see [query-editor](https://github.com/alexanderzobnin/grafana-zabbix/tree/query-editor) and [cache-service](https://github.com/alexanderzobnin/grafana-zabbix/tree/cache-service) branch. In new version hosts and metrics will be cached and datasource will sends only history requests.

**Comment by Krazylee** [comment]
That's great, a really nice refactor and enhancement, looking forward to it!
Can I pull cache-service branch and use it now, do I need upgrade grafana to 3.0, my current version is 2.6.0

**Comment by alexanderzobnin** [comment]
You can pull [query-editor](https://github.com/alexanderzobnin/grafana-zabbix/tree/query-editor) branch (it contains all cache-service changes) and use it with Grafana 3.0 nigtly builds (http://grafana.org/download/builds.html). New plugin version still in active development and may contains many bugs - just ignore it.

**Comment by Krazylee** [comment]
Nice, I will test this, small bugs doesn't matter, just tell me if I can offer any help

**Comment by Krazylee** [comment]
@alexanderzobnin  Hi, I've tried the newest code today.The performance improvement is very huge.
There are three issues here:
1. the templating has some bugs, it seems it's due to the differences between the zabbixAPI and zabbixAPIWrapper, some apis in zabbixAPIWrapper is not in zabbixAPI anymore.
When I want to list the servers(query: $group.*), it will broke.
2. the query editor params are missing like filter, item name, are they in the plan?
3. when changing tabs in query editor, it will request history.get 3 times, this will slow the metric tab a lot.
Not sure this is the behavior of grafana or grafana-zabbix.

Are you working on this issues, I think I can choose one aspect and work on it to help this move forward.

**Comment by alexanderzobnin** [comment]
@Krazylee 
1. I'm almost done new query editor and templating is a next part.
2. New query editor has incompatible structure and I think about some tools for migration from previous versions.
3. I'm see it too. Need to check editor initialization part.

If you have a relatively large environment you can help me by testing new code (especially performance).
Thanks!

**Comment by alexanderzobnin** [comment]
@Krazylee I fixed templates and query editor lags. Checkout latest code from grafana-3.0 branch.

**Comment by Krazylee** [comment]
so efficient! I will test it asap.

**Comment by clems94** [comment]
Hello alexanderzobnin

Many thanks for your work on zabbix plugin for grafana.

I installed grafana 2.6 and zabbix plugin 2.5.1 in production but i still have performance issues. 

I try to test grafana 3.0 nigthly build with zabbix plugin version 16a7786 yesterday on test but it does not work. i ve got the error below :

Plugin Error
Failed to find exported plugin component for ds-config-zabbix

**Comment by alexanderzobnin** [comment]
@clems94 in latest build api for plugins was broken. Wait a little - I'll fix it or use earlier 3.0 builds.

**Comment by alexanderzobnin** [comment]
@clems94 I fixed query editor and you can test latest plugin version from develop branch with Grafana 3.0.

**Comment by clems94** [comment]
hi Alexender

Many thanks for the work.

I tried the last grafana3.0 branch on my test environnement and i still have the error  

Plugin Error
Failed to find exported plugin component for ds-config-zabbix

**Comment by alexanderzobnin** [comment]
@clems94 try develop branch, not grafana-3.0

**Comment by clems94** [comment]
Alexander 

I installed the develop branch, i don't see error but i do not see the configuration property on zabbix datasource 

![image](https://cloud.githubusercontent.com/assets/16476918/12981456/fd997636-d0e0-11e5-9245-2d1e8ce26dad.png)

**Comment by alexanderzobnin** [comment]
@clems94 Yes, this is a bug. It may be Grafana bug, not shure. Need a little time time to fix it.

**Comment by alexanderzobnin** [comment]
@clems94 Now fixed. Try latest commit from develop.

**Comment by clems94** [comment]
@alexanderzobnin 

Good job

I can now use zabbix datasource select environnement and hosts but application and item do not work.

**Comment by alexanderzobnin** [comment]
@clems94  Can you describe this bug with more details?

**Comment by alexanderzobnin** [comment]
Also, which Zabbix version you use? If 3.0, try to leave application field empty.

**Comment by clems94** [comment]
@alexanderzobnin 

I use Redhat/Centos (64bit) .rpm package	grafana-3.0.0-pre1.x86_64.rpm	12/02/2016, 10:24:29

Here you can see a print screen 

![image](https://cloud.githubusercontent.com/assets/16476918/13006664/d54bc882-d18a-11e5-8ece-c38afaed85e5.png)

**Comment by alexanderzobnin** [comment]
Which Zabbix version?

**Comment by clems94** [comment]
zabbix 2.2.8

**Comment by alexanderzobnin** [comment]
Can you open development tools -> console and look at ZabbixCachingProxy variable. Is it contains groups, hosts, applications and items?

**Comment by clems94** [comment]
ZabbixCachingProxy {zabbixAPI: ZabbixAPI, ttl: 3600000, _groups: undefined, _hosts: undefined, _applications: undefined…}

TypeError: Cannot read property 'hostid' of undefined

**Comment by alexanderzobnin** [comment]
Can you provide full error trace?

**Comment by clems94** [comment]
TypeError: Cannot read property 'hostid' of undefined
    at boot.a045d616.js:39
    at Function._a (boot.a045d616.js:38)
    at zabbixCache.js?bust=1455280570401:197
    at boot.a045d616.js:38
    at hd (boot.a045d616.js:39)
    at Function._a (boot.a045d616.js:38)
    at convertApplications (zabbixCache.js?bust=1455280570401:189)
    at zabbixCache.js?bust=1455280570401:61
    at h (boot.a045d616.js:35)
    at boot.a045d616.js:35

**Comment by alexanderzobnin** [comment]
It seems like Zabbix 2.2-specific bug.

**Comment by alexanderzobnin** [comment]
```js
function convertApplications(applications) {
      return _.map(_.groupBy(applications, 'name'), function(value, key) {

        // Hack for supporting different apis (2.2 vs 2.4 vs 3.0)
        var hostField = value['hosts'] ? 'hosts' : 'host';

        return {
          name: key,
          applicationids: _.map(value, 'applicationid'),
          hosts: _.uniq(_.map(_.flatten(value, hostField), 'hostid'))
        };
      });
    }
```

**Comment by alexanderzobnin** [comment]
I need to make some test with Zabbix 2.2.

**Comment by alexanderzobnin** [comment]
My hack don't work :smile:

**Comment by clems94** [comment]
do it works with zabbix 2.4 ?

**Comment by alexanderzobnin** [comment]
Yes, with Zabbix 2.2 it works.

**Comment by clems94** [comment]
i think you mad an error on your last post :-)

**Comment by alexanderzobnin** [comment]
Sorry, works with 2.4 of course!

**Comment by volter** [comment]
I saw this too. I git-bisected it. You introduced that with fa10d76e2b5278b62843a0f1cb82ef197f384fc4, if memory serves me right.

**Comment by alexanderzobnin** [comment]
@volter Yes, because application.get in Zabbix 2.2 use a bit different option - selectHost instead selectHosts in zabbix 2.4. Really strange change for minor version.

**Comment by kli-aa** [comment]
@alexanderzobnin  sorry for the delay.
I need to catch up your work, which branch should I test now with the newest grafana nightly build version.

BTW, is it possible to choose another storage for cache instead of memory, like localStorage or browser cache.

**Comment by Krazylee** [comment]
@alexanderzobnin  sorry for the delay.
I need to catch up your work, which branch should I test now with the newest grafana nightly build version.

BTW, is it possible to choose another storage for cache instead of memory, like localStorage or browser cache?

**Comment by alexanderzobnin** [comment]
@Krazylee I also think about localStorage, it's good idea. Need some time to implemet it.

**Comment by clems94** [comment]
Hello

@alexanderzobnin  i tried to install developp branch on my test environnement today.

It works fine with Zabbix 2.4
With Zabbix 2.2 i can select environnement, host, application and item but it is very very slow

I've got the error below when i select the panel zabbix trigger 

XHR error (404 Not Found) loading http://euisats894:3000/public/app/features/panel/panel_meta.js?bust=1455550376644 Error loading http://euisats894:3000/public/app/features/panel/panel_meta.js as "app/features/panel/panel_meta" from http://euisats894:3000/public/plugins/triggers/module.js

**Comment by alexanderzobnin** [comment]
@clems94 Trigger panel still broken, I fixing it now. What exactly is slow?

**Comment by clems94** [comment]
it takes 30 sec to show an item.

**Comment by alexanderzobnin** [comment]
How many items in your Zabbix instance?

**Comment by clems94** [comment]
88 items on the host i try to graph.

**Comment by alexanderzobnin** [comment]
No, total number of items.

**Comment by clems94** [comment]
49 000 on the table item.

**Comment by alexanderzobnin** [comment]
May be it's a reason.

**Comment by alexanderzobnin** [comment]
Each time you place input in textbox plugin filter metrics. In your case it slow. I need to make some optimizations.

**Comment by alexanderzobnin** [comment]
@clems94 Trigger Panel now fixed.

**Comment by Krazylee** [comment]
@alexanderzobnin Hi, I noticed the query editor lags(change between general and metric tabs) does not trigger network requests anymore, but it is still slow, almost 9 seconds.

the local cache is like this
```
ZabbixCachingProxy: 
_applications: Array[85]
_groups: Array[32]
_hosts: Array[240]
```

Not sure about it, but maybe related to angular digest loop, can you reproduce this?
![image](https://cloud.githubusercontent.com/assets/557165/13065845/764ddd02-d49b-11e5-9912-ea0dbdc82904.png)

**Comment by alexanderzobnin** [comment]
I'll try to reproduce this lags in test zabbix server with several hundreds of hosts.

**Comment by alexanderzobnin** [comment]
@Krazylee @clems94 I've tried to test query editor with test Zabbix server with 400 hosts and 15000 items and all works without lags. Can you describe your problem in details?

**Comment by alexanderzobnin** [comment]
I also doing some optimizations now. So metric filtering will be faster.

**Comment by clems94** [comment]
@alexanderzobnin 

hi alexander it works fast with zabbix 2.4.7 but not with zabbix 2.2.8

**Comment by alexanderzobnin** [comment]
@clems94 Do you have equal number of hosts and items on 2.2 and 2.4?

**Comment by clems94** [comment]
@alexanderzobnin 

Hello

i have 568 host on zabbix 2.2 and 2 host on 2.4

**Comment by alexanderzobnin** [comment]
@clems94 of course - 568 vs 2 hosts :smile: I will try to test with more hosts on my test server.

**Comment by alexanderzobnin** [comment]
Fixed in latest version.
