### ISSUE TITLE
Plugin doenst work anymore after Zabbix/Grafana Upgrade to v6.4.2 and v9.5.1

### ISSUE THREAD

**Issue by OMSKremer** [alexanderzobnin/grafana-zabbix#1629]
**Describe the bug**
I no longer receive any data from localhost Zabbix Server. Grafana Zabbix-Plugin Connection test says it's ok ("Zabbix API version: 6.4.2, DB connector type: postgres").

I updated Zabbix from 6.4.1 to 6.4.2, Grafana from 9.5.0 to 9.5.1 and the plugin from 4.3.0 to 4.3.1 (I downgraded again to 4.3.0. but still the same problem, so i think zabbix server breaking changes oder grafana breaking changes?)

When i directly explore the postgre connection in Grafana i receive data normally. But the grafana-zabbix plugin does not seem to use this connection properly. (But what speaks against the suspicion of an error on the part of Zabbix or Grafana?)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.5.1   | 6.4.2  | 4.3.1                 |

![2023-04-30 19_44_37-](https://user-images.githubusercontent.com/1644266/235368126-77e5a636-8724-46e9-a4e4-60247ded7124.png)

**Comment by Foxi352** [comment]
For what it's worth: I have the same problems than mentioned in this ticket. (+ the missing dashboard from another ticket)

Installed on newly created Debian 11 VM:

- Zabbix 6.4.2
- Grafana 9.5.1
- Grafana-Zabbix plugin 4.3.1
- PostgresQL 15.2-1 with TimeScaleDB 2.10.3

Less important, but still: In plugin configuration the "Dashboard" tab does not work. Files do not seem to exist on disk ?
![Screenshot 2023-05-02 at 14 03 19](https://user-images.githubusercontent.com/5746932/235660959-8457c1c8-1b12-4779-8cfb-0efcbbc1c69d.png)

Blocking issue: Plugin does not get data from Zabbix. Tested with and without direct DB connection in plugin.

Plugin Test works:
![Screenshot 2023-05-02 at 14 02 41](https://user-images.githubusercontent.com/5746932/235660826-2bca8cdf-11e6-4607-9564-285b42e4f8f2.png)

I can also access the tables from PostgreSQL data source. But Zabbix datasource stays empty, without any errors.
I once got the host groups to show up, but host was always empty. After server restart i was no more able to even get the host groups populated.

![Screenshot 2023-05-02 at 14 06 21](https://user-images.githubusercontent.com/5746932/235661605-8903520e-5983-4112-8a29-3eec7c64b5d0.png)

**Comment by ecrichton0** [comment]
Same thing here, I just deployed Zabbix in docker earlier in the week and it was working fine. What's confusing me is that nothing should have updated, Zabbix is on V 6.4.2 but it has always been so why did it stop working all of a sudden?

**Comment by mortenaatkartverket** [comment]
I know it doesnt solve the problem, but you can point to a specific item ID, and it will show the graph for that. So there is some kind of connection...

**Comment by JihadArfat** [comment]
Is this problem still ongoing? Has anyone discovered a workaround? 

Thanks in advance!

**Comment by riversideneyon** [comment]
Same here, Plugin test works but in the query doesn't show anything like groups etc.
Zabbix : 6.4
Grafana : v10.2.2
Plugin : 4.4.4

**Comment by oti-mandrews** [comment]
Hi all,

We had the same issue in our Zabbix-Grafana implementation. The problem was that our grafana user account in Zabbix didn't have permissions to the host groups. Once we configured the grafana user account within Zabbix to have permissions on the host groups, it then worked.
