### ISSUE TITLE
grafana 6.4.2 edit Problems panel faild.

### ISSUE THREAD

**Issue by xiaoxue999** [alexanderzobnin/grafana-zabbix#817]
grafana 6.4.2 edit Problems panel faild.
![1](https://user-images.githubusercontent.com/22721577/66633721-0fe05b80-ec3e-11e9-92d6-1ea341146ce1.png)
![2](https://user-images.githubusercontent.com/22721577/66633733-15d63c80-ec3e-11e9-83bf-96ba88e7baff.png)
![3](https://user-images.githubusercontent.com/22721577/66633741-1969c380-ec3e-11e9-8a8d-dd9b7721ed4d.png)

**Comment by dannyhanes** [comment]
I am having the same issue. This is the result after clicking "edit" 

<img width="554" alt="Screen Shot 2019-10-11 at 10 42 29 AM" src="https://user-images.githubusercontent.com/3778687/66660831-e9a5c600-ec13-11e9-92b2-6f4dec4b6536.png">

**Comment by eans-tsi** [comment]
I'm using plugin v3.10.4 with Grafana v6.4.2 and I'm getting the same errors when trying to edit a "Zabbix Problems" panel/widget.

**Comment by duuz** [comment]
+1

**Comment by mjtrangoni** [comment]
@alexanderzobnin we need a new release with [this](https://github.com/alexanderzobnin/grafana-zabbix/commit/a652eafc46bb4e25c034243d506f2513c08f1f41). What's about a quick 3.10.5 release before going to 3.11?

**Comment by pierrottls** [comment]
Hello same issue with plugin v3.10.4 with Grafana v6.4.2
did someone found a temporary fix, for now im using panels' creation links to edit my panel.

**Comment by valentinrueeck** [comment]
+1
same with adding query to new panel in new dashboard with prometheus 2.13.0 and grafana 6.4.2

**Comment by heshammhafez** [comment]
+1

**Comment by juannvalencia** [comment]
Hi, same problem with same versions

**Comment by winderickxeli** [comment]
+1

**Comment by ramasif** [comment]
+1

**Comment by katsil** [comment]
+1

**Comment by sadamkim** [comment]
+1

**Comment by pancake62** [comment]
+1 as well.

**Comment by Aleksey-Maksimov** [comment]
+1

**Comment by manojsivan** [comment]
+1

**Comment by darkydash** [comment]
+1

**Comment by amar3lo** [comment]
+1

**Comment by joaoceragioli** [comment]
+1

**Comment by ramasif** [comment]
Okay, so I don't know if this will fix it for everyone else, but as the error message states: "Grafana has likely been updated.."... Well updating Grafana to the newest version actually fixed it for me. 

As stated in the release notes [here](https://github.com/grafana/grafana/releases) 

> "Table: Proper handling of json data with dataframes." 

also stating 

> "What this PR does / why we need it:
> When using Raw Document query with Elasticsearch there's a special response from datasource that is used which includes a type field with the value json. In the table panel there is a transformation for JSON data which up until this fix didn't work at all due to the new data structure we call data frames."

Hope this helps.

**Comment by manojsivan** [comment]
Hi, Updated grafana to latest and issue still persists.  Same error when you try to create a new dashboards.

**Comment by heshammhafez** [comment]
Me too

**Comment by maxlehot1234** [comment]
+1 @alexanderzobnin Same thing happened to me:
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.4.3    | 4.2.6  | 3.10.4                      |

Just weird since problems list works, but we can't edit the panel anymore.

An update of the grafana-zabbix plugin will probbaly fix this ;)

Thanks in advance

**Comment by Unbr8kable** [comment]
+1

**Comment by Grzyboll** [comment]
+1

**Comment by borjasueiro** [comment]
+1

**Comment by alexanderzobnin** [comment]
That's a bug due to changes in Grafana. Looks like panel editor tries to execute panel queries even if 
 `skipDataQuery` set to `true` in plugin.json. I will open an issue in Grafana as well, but it looks like I should do something with problems panel query format. Using `targets` as a map instead of array causes a lot of problems.

**Comment by ta391993** [comment]
Just confirming exact same for me too; 
Zabbix 4.2.6
Grafana 6.4.3
Zabbix-Plugin 3.10.4

**Comment by maxlehot1234** [comment]
Any news on this?

**Comment by randomayzer** [comment]
the same terrible thing :(
after update to last grafana version all dashboards with plugin not edditable 
sad...

**Comment by oscar-munoz** [comment]
Zabbix 4.2.7. 
Grafana 6.4.4 ( no fix the issue )
Zabbix-Plugin 3.10.4

**Comment by gsrcobr** [comment]
It's not possible also remove "functions" applied to queries / sources from zabbix

![grafana-zabbix](https://user-images.githubusercontent.com/547401/68778655-3b29e200-0612-11ea-8123-5d8f7c73ec73.png)

Clicking in any area of a function enables only editing label or parameters, but you are not able to remove applied function

alexanderzobnin-zabbix-app @ 3.10.4
grafana-6.4.4-1.x86_64

**Comment by maxlehot1234** [comment]
@alexanderzobnin You are probably busy but do you have an ETA for 3.11 version? Too many errors/bugs that prevent all of us to "work" properly.

Thanks again and maybe you can push the 3.11 version and another 3.11.X later to fix other bugs.

That could be great.

**Comment by StaelensJarne** [comment]
I also have this issue.

Does anyone know it there is a workaround?
Or how to temporary solve this issue?

I use grafana version 6.4.4 and alexanderzobnin-zabbix-app version 3.10.4.

**Comment by jwhclw** [comment]
i have the same issue. 
grafana 6.4.3
zabbix-plugin 3.10. 4

**Comment by StaelensJarne** [comment]
Is there a workaround for this problem?
Or has anyone found how to edit these panels?

Because I think this is a well known issue.

**Comment by maxlehot1234** [comment]
Well we all have to wait the 3.11 release which will probbaly take weeks...

The actual dev was quite busy I think and doesn't want to release a 3.11 and a 3.11.X later.......


Thats just really bad and we need to deal with this. @alexanderzobnin doesn't reply to actual tickets or doesn't reply to us for more than 20 days now :(

We just need to still put our problem in this ticket so he can finally push a fixed version...

**Comment by Unbr8kable** [comment]
When you want do edit your panel you can do this As a workaround:
You can create a new Trigger Panel, But you Need to know all settings you did there before.

So I still wait for the Update too...

**Comment by maxlehot1234** [comment]
> When you want do edit your panel you can do this As a workaround:
> You can create a new Trigger Panel, But you Need to know all settings you did there before.
> 
> So I still wait for the Update too...

Doesn't seems to work for me. Still having issue :( I will wait for an update in 2020 (I hope)

**Comment by leoplanchin** [comment]
> 
> 
> When you want do edit your panel you can do this As a workaround:
> You can create a new Trigger Panel, But you Need to know all settings you did there before.
> 
> So I still wait for the Update too...

You can edit your panel after creating it by passin through "More..." and "Panel JSON" it works for me, it's harder than the usual way but in the wait, it's still better than recreating your panel each time you want to change it

**Comment by StaelensJarne** [comment]
I have found a more permanent solution.

Downgrading to Grafana version 6.0.0. This is the version before this issue.

**Comment by Blogshot** [comment]
> I have found a more permanent solution.
> 
> Downgrading to Grafana version 6.0.0. This is the version before this issue.

That is not a solution but a workaround.

**Comment by zelfix** [comment]
+1

**Comment by seyacat** [comment]
+1

**Comment by maxlehot1234** [comment]
+1 @alexanderzobnin ? Still alive?

**Comment by juniorsaldanha** [comment]
Same problem for me too,
Zabbix Server 4.0 LTS and Grafana 6.4.4 but im with this problem since 6.4.2 or 6.4.3 (i dont remember, but i updated to see if would solve, but nothing). I need help to this,

**Comment by maxlehot1234** [comment]
> Same problem for me too,
> Zabbix Server 4.0 LTS and Grafana 6.4.4 but im with this problem since 6.4.2 or 6.4.3 (i dont remember, but i updated to see if would solve, but nothing). I need help to this,

No fix will be released soon. WE all wait for more than a month without a reply from the dev...
Probably 2020?

**Comment by Chumachos** [comment]
Zabbix 4.4, Zabbix plugin 3.10.4 and Grafana 6.5.0 I'm with similar problem: 

> TypeError: t.queries.map is not a function

**Comment by elsopapa** [comment]
+1

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
6.4.4 | 4.4.0 | 3.10.4

**Comment by renatoborges78** [comment]
+1
TypeError: n.targets.map is not a function

**Comment by ywj198** [comment]
+1

**Comment by carlgan** [comment]
+1

Grafana	Zabbix	Grafana-Zabbix Plugin
6.5.1 	4.4.0 	3.10.4

Grafana	Zabbix	Grafana-Zabbix Plugin
6.5.1 	4.0.13 	3.10.4

**Comment by piojak** [comment]
+1

**Comment by brunoemr** [comment]
+1

**Comment by brunoemr** [comment]
Same error with "t.queries.map":

An unexpected error happened
Details
TypeError: t.queries.map is not a function

    in t
    in div

**Comment by maxlehot1234** [comment]
@alexanderzobnin ?? Please, push an update

**Comment by leferocha** [comment]
+1

**Comment by robpuretz** [comment]
Zabbix-Server 4.41
Zabbix plugin 3.10.3
Grafana 6.4.0
I have the same problem

**Comment by kajohe** [comment]
Zabbix-Server 4.4.1
Zabbix plugin 3.10.4
Grafana 6.4.4
Same issue persists.

Also, variables can not be used in the 6.4 Grafana for the Zabbix Problems panel.

**Comment by StaelensJarne** [comment]
> Also, variables can not be used in the 6.4 Grafana for the Zabbix Problems panel.
In Grafana version 6.0.0 I can use variables in the Zabbix Problem panel without any problems.

**Comment by naigamo** [comment]
+1

**Comment by guliangsi** [comment]
Same problem for us too,
Grafana 6.5.1
Zabbix Plugin 3.10.4

TypeError: t.queries.map is not a function

**Comment by mrhernandes** [comment]
I downgraded to version 6.3.6.
the panel works again very well.

**Comment by elsopapa** [comment]
Did use the same db ?

**Comment by gordonpt** [comment]
+1

**Comment by maxlehot1234** [comment]
@alexanderzobnin Seriously?? 2 months and no update?? Thats really bad :(

You see the amount of people having issue witgh the same thing? Release a 3.11 version and a 3.11.1 later?

Thanks

**Comment by mglennon** [comment]
Just installed Grafana this morning. Zabbix and Grafana (and plugin) are fresh and new - having the same issue. I can create the Dashboard but once created I can't go back and edit it.
![2019-12-19 11_01_33-Problems - Grafana](https://user-images.githubusercontent.com/5652065/71188426-f4518c80-224e-11ea-9288-9ca060d54da7.png)

**Comment by mrhernandes** [comment]
yes same db mysql

**Comment by havedill** [comment]
+1

**Comment by Chumachos** [comment]
> I downgraded to version 6.3.6.
> the panel works again very well.

How can I downgrade to this version?

**Comment by alexanderzobnin** [comment]
Fixed. I'm going to prepare patch release this week.

**Comment by juannvalencia** [comment]
Solved,
Thank you very much for your incredible work and dedicated time.

**Comment by rickrb** [comment]
@alexanderzobnin same issue still happening on v6.5.2. Can you please check?

![image](https://user-images.githubusercontent.com/5422953/77492318-0844f580-6e1f-11ea-87de-b36ebfb6fa1b.png)

**Comment by evgenymarkov** [comment]
Same issue in Grafana 9.2.0

```
TypeError: t.map is not a function

    at Io (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:363:1276)
    at div
    at div
    at http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:2942:48
    at div
    at http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:426:1562
    at div
    at div
    at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:6538)
    at div
    at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:8487)
    at div
    at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:6538)
    at div
    at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:8487)
    at Zt (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:14074)
    at div
    at div
    at div
    at b (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:5743:1111)
    at Si (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:443:1519)
    at g (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:920808)
    at WithTheme(Connect(Si))
    at Aa (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:566:7310)
    at DashboardPage
    at g (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:920808)
    at Suspense
    at c (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:1194:301)
    at fc (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8746:362)
    at t (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:936126)
    at t (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:938147)
    at main
    at Ql (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8707:13067)
    at t (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:932744)
    at div
    at o (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:2035:4306)
    at t.KBarProvider (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:182746)
    at l (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:6089:19180)
    at c (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:1194:301)
    at u (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:1194:855)
    at y (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:2813677)
    at tc (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8743:21930)
    at l (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:918853)
    at qc (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8759:115)
```

**Comment by Nabeel-Falconi** [comment]
> Same issue in Grafana 9.2.0
> 
> ```
> TypeError: t.map is not a function
> 
>     at Io (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:363:1276)
>     at div
>     at div
>     at http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:2942:48
>     at div
>     at http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:426:1562
>     at div
>     at div
>     at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:6538)
>     at div
>     at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:8487)
>     at div
>     at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:6538)
>     at div
>     at n (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:8487)
>     at Zt (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:99:14074)
>     at div
>     at div
>     at div
>     at b (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:5743:1111)
>     at Si (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:443:1519)
>     at g (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:920808)
>     at WithTheme(Connect(Si))
>     at Aa (http://127.0.0.1:53000/public/build/DashboardPage.ce4ef2ce392cfb999309.js:566:7310)
>     at DashboardPage
>     at g (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:920808)
>     at Suspense
>     at c (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:1194:301)
>     at fc (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8746:362)
>     at t (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:936126)
>     at t (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:938147)
>     at main
>     at Ql (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8707:13067)
>     at t (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:932744)
>     at div
>     at o (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:2035:4306)
>     at t.KBarProvider (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:182746)
>     at l (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:6089:19180)
>     at c (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:1194:301)
>     at u (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:1194:855)
>     at y (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:2813677)
>     at tc (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8743:21930)
>     at l (http://127.0.0.1:53000/public/build/5290.5730ffe229a3937f6f65.js:2:918853)
>     at qc (http://127.0.0.1:53000/public/build/3593.d02472c827ce6c0cf5b9.js:8759:115)
> ```

I am facing the same issue when I select Influx DB in Grafana Alerts.
![image](https://user-images.githubusercontent.com/123537983/218444783-5d0a4879-8c79-4ed2-b686-99f0f9d5002f.png)

**Comment by Roanmh** [comment]
I saw this as well on 9.2.2. But, a hard refresh solved it for me.
