### ISSUE TITLE
Empty Problem List in 3.12.x

### ISSUE THREAD

**Issue by clouddoubt** [alexanderzobnin/grafana-zabbix#955]
After upgrading to 3.12.0, I have an issue with the Issue List.
I did some tests and when I put it on type "the table", I managed to get some information that can help.
The last print is from version 3.11

![zabbix 2](https://user-images.githubusercontent.com/34309594/82633629-f17a0f80-9bd1-11ea-9a29-373b74763c8a.PNG)

![zabbix 1](https://user-images.githubusercontent.com/34309594/82633626-f048e280-9bd1-11ea-85ee-34cd5167368d.PNG)
![zabbix 3](https://user-images.githubusercontent.com/34309594/82633631-f17a0f80-9bd1-11ea-8568-9696c96af02e.PNG)

**Comment by alexanderzobnin** [comment]
@clouddoubt what's a Zabbix version you're using?

**Comment by vtarakhan** [comment]
I have the same problem when the description contains a space
Error "Cannot read property 'description' of undefined"

**Comment by alexanderzobnin** [comment]
@vtarakhan could you show an example?

**Comment by Tulkis** [comment]
Hi!
Here the same problem with:
Zabbix version 4.4.8
Grafana version 6.5.2
Plugin version 3.12.0
Regards.

**Comment by Tulkis** [comment]
Another thing might help, now I can see the correct values returned by api query in query inspector, but panel still showing "! o is undefined":
![imagen](https://user-images.githubusercontent.com/10271541/82652737-696e2700-9c1e-11ea-97b3-653b62a8231d.png)

**Comment by alexanderzobnin** [comment]
@Tulkis could you expand one of the returned triggers in result?

**Comment by Tulkis** [comment]
Of course, here is:
![imagen](https://user-images.githubusercontent.com/10271541/82654219-aaffd180-9c20-11ea-8ab5-542503d82e51.png)

**Comment by Tulkis** [comment]
For your information:
I have another grafana & zabbix (same version) and just updated grafana to 6.7.3 and the problem solved with the latests plugin version.

**Comment by Tulkis** [comment]
> 
> 
> For your information:
> I have another grafana & zabbix (same version) and just updated grafana to 6.7.3 and the problem solved with the latests plugin version.

I did more tests and upgraded grafana on failing environment. I recreated the datasource on different organizations and there is no consistent result. Some times it solves the panel issues and other times not..

**Comment by renanyuu** [comment]
Hi,
I also have this problem after upgrading the plugin.
Running grafana ver 6.4.2 and zabbix 3.4.2. Other zabbix metrics are working just fine.

**Comment by Tulkis** [comment]
Problem solved with 3.12.2

**Comment by karl-j** [comment]
@Tulkis, confirmed. Problem solved with 3.12.2 without doing any change to the panel.
I'm using Grafana 7.0.1

Thank you!

**Comment by renanyuu** [comment]
3.12.2 did not solve the issue for me on grafana 6.4.2.
Tried upgrading grafana to 7.0.1 and the error when adding a new panel disappears but it still does not display any problems from zabbix. 
![Screenshot_194](https://user-images.githubusercontent.com/647965/83275174-1a506500-a1cf-11ea-9f37-c4795b5861bf.png)

**Comment by alexanderzobnin** [comment]
@renanyuu do you get any error? Do you see that problems in Zabbix?

**Comment by renanyuu** [comment]
If I create a new panel with Zabbix Problems it says "No problems found" but query inspector still looks ok showing problems that exist in Zabbix.
grafana.log-file shows no error.

I sometime can get this to happen when I create a new panel and select zabbix problems.
![Screenshot_196](https://user-images.githubusercontent.com/647965/83409366-8d96e880-a414-11ea-9007-956bfe1f1905.png)

**Comment by danidosreis** [comment]
I also upgraded to plugin version 3.12.2 and Grafana 6.6.0 and still have problems with the 'Zabbix Problem' chart. The version of Zabbix I use is 3.2.11.

![image](https://user-images.githubusercontent.com/39527066/83518119-71488980-a4b0-11ea-9f44-ac536a0bcde1.png)

![image](https://user-images.githubusercontent.com/39527066/83518147-7b6a8800-a4b0-11ea-8082-97486bda062c.png)

![image](https://user-images.githubusercontent.com/39527066/83518174-82919600-a4b0-11ea-8deb-9fd3a8f11aea.png)

https://user-images.githubusercontent.com/39527066/83182165-4fd84e00-a0fc-11ea-9a4e-113d153dad8f.png

**Comment by lazycoder-ru** [comment]
Same issue. Problems panel is empty, but query inspector shows data in response. Issue exists on grafana 6.x and 7.x, plugin version 3.12.2, zabbix version 3.4

**Comment by rawsGit** [comment]
Code is functional while running 
Zabbix 3.4.13
Grafana v7.0.3 
Zobnin Plugin version 3.11.0

**Comment by lazycoder-ru** [comment]
Yes, its work on plugin version 3.11.0. Thanks!

**Comment by renanyuu** [comment]
Hi, I can also confirm that it works when downgrading to plugin version 3.11.0
Grafana v7.0.3
Zabbix V3.4.2

**Comment by AndreyRuban** [comment]
Hi Hey. Plugin 3.12.3 does not show Zabbix Problem chart Grafana v7.0.5
Zabbix V3.4.14
